name: Pipeline Avancée

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2
      - name: Installation des dépendances
        run: npm install
      - name: Build du code
        run: npm run dev
      - name: Archive du build
        uses: actions/upload-artifact@v4
        with:
          name: build-results
          path: dist
